input_dir: 
   class: Directory
   path: weather
temp_dir: /tmp/tmp
output_file: /tmp/config.yaml
var_name: precipitation
bounding_box: "23.995416666666, 6.532916666667, 28.020416666666, 9.566250000000"
xres_arcsecs: 30
yres_arcsecs: 30